apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: iris
  namespace: iris-serving
spec:
  predictor:
    canaryTrafficPercent: 10
    containers:
      - name: kserve-container
        image: ghcr.io/REPLACE_ME/iris-inference:REPLACE_WITH_NEW_SHA
        env:
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow.model-registry.svc.cluster.local:5000
          - name: MODEL_URI
            value: models:/iris-classifier@candidate

