apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iris
  namespace: iris-serving
spec:
  selector:
    matchLabels:
      serving.kserve.io/inferenceservice: iris
  namespaceSelector:
    matchNames: [iris-serving]
  endpoints:
    - port: http-usermetric
      path: /metrics
      interval: 15s

